remote_theme: chrisrhymes/bulma-clean-theme@v0.14.0

lang: en
title: Fortress64
description: Securing Your Digital Privacy.
baseurl: "/"
url: "https://ptx64.github.io/"
permalink: pretty

fixed_navbar: top
theme_color: '#dddddd'
force_theme: light

show_sidebar: false
menubar: menu
